name: Deploy pages

on:
  push:
    branches: ["master", "main"]
    paths-ignore:
    - '**/*.md'
    - '**/*.github'
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  pages:
    if: success()
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4 #https://github.com/actions/checkout
        
      - name: Download build artifacts
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
            name: pages
            path: release

      - name: Deploy gh-pages
        continue-on-error: true
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: dist
